from collect_strategies.base_strategy import BaseStrategy
from collect_strategies.sum import SumStrategy
from collect_strategies.average import AverageStrategy
from collect_strategies.factory import FactoryStrategy
