from collect_strategies.base_strategy import BaseStrategy
from collect_strategies.sum import SumStrategy
from collect_strategies.average import AverageStrategy
from collect_strategies.factory import FactoryStrategy
from collect_strategies.standar_deviation import StandardDeviationStrategy
from collect_strategies.min import MinStrategy
from collect_strategies.max import MaxStrategy
